public without sharing class L_Constants {
	public static final Decimal TRUCK_SERVICE_PERCENTAGE = 0.1;
    public static final String ORDERPAID_STATUS = 'Paid';
    public static final String ORDERRECEIVED_STATUS = 'Received';
    public static final String OPP_CLOSED_STATUS = 'Closed Won';
    
    public static final String HTTP_METHOD_GET = 'GET';
    public static final String INT_CLIENTID_VALUE = 'b903e91e6c6542a3a4a6e800f37f95ea';
    public static final String INT_CLIENTID_APINAME = 'client-id';
    public static final String INT_CLIENTSECRET_VALUE = '4d73e495F84E4c47B8a8E37C8F8B96b3';
    public static final String INT_CLIENTSECRET_APINAME = 'client-secret';
    public static final String INT_CORRELATIONID_APINAME = 'correlation-id';
    public static final String INT_ENDPOINTURL_VALUE = 'https://eu1.anypoint.mulesoft.com/mocking/api/v1/links/267cf127-5cc9-499d-bb5c-fe2d447aa99d/JOINTHEDIGITALHUB/WMAH05ZZZ4B011671';
}